platform :ios, '8.0'

target :SAPublicModule do
pod 'MBProgressHUD', '~> 1.0.0'
 pod 'Masonry', '~> 1.0.2'
 pod 'SDWebImage', '~> 4.0.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'AFNetworking', '~> 3.1.0'
end
